### ISSUE TITLE
Cannot load gsose.dll

### ISSUE THREAD

**Issue by SamZhangQingChuan** [chrisnas/DebuggingExtensions#3]
Hi there, thanks for creating the tools first.

I encountered the following error. Could you please take a look?

```
0:006> .load C:\Repos\DebuggingExtensions\binaries\gsose-1.6.1_x64\gsose.dll
The call to LoadLibrary(C:\Repos\DebuggingExtensions\binaries\gsose-1.6.1_x64\gsose.dll) failed, Win32 error 0n193
    "%1 is not a valid Win32 application."
Please check your debugger configuration and/or network access.
```

**Comment by chrisnas** [comment]
Hi @SamZhangQingChuan,
Was it related to x86/x64 issue?

**Comment by SamZhangQingChuan** [comment]
Hi @chrisnas I suspect so. 

Also, I cannot build gsose locally. Could you please take a look?

![image](https://user-images.githubusercontent.com/8025859/122150277-f621fd80-ce8f-11eb-8d5e-99341b51e271.png)
